# Generated by Django 4.2.27 on 2026-01-09 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tg_chat_id",
                    models.BigIntegerField(
                        unique=True, verbose_name="Telegram Chat ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Chat Title"
                    ),
                ),
                (
                    "chat_type",
                    models.CharField(
                        choices=[
                            ("group", "Group"),
                            ("supergroup", "Supergroup"),
                            ("private", "Private"),
                            ("channel", "Channel"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Chat Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tg_message_id",
                    models.BigIntegerField(verbose_name="Telegram Message ID"),
                ),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(verbose_name="Sent At")),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "unique_together": {("chat", "tg_message_id")},
            },
        ),
    ]
