# Generated by Django 4.2.27 on 2026-01-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chat_pinned_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Reply To TG Message ID'),
        ),
    ]
