# Generated by Django 4.2.27 on 2026-01-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="extracted_deadlines",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
