# Generated by Django 4.2.27 on 2026-01-10 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_extracted_deadlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vector_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='entry_type',
            field=models.CharField(choices=[('deadline', 'Deadline'), ('link', 'Link'), ('explanation', 'Explanation'), ('generic', 'Generic Info')], max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='course_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='analysis.coursetask'),
        ),
    ]
