# Generated by Django 4.2.27 on 2026-01-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_coursetask_knowledgeentry_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='task_type',
            field=models.CharField(choices=[('one_time', 'Разовая'), ('periodic', 'Периодическая')], default='one_time', max_length=20),
        ),
    ]
